contentColumnType: text
fieldGroup: 43acc95b-a439-41bf-b60b-aee8c47f4984
handle: businessAddress2
instructions: 'Address line 2 of the business'
name: 'Business Address 2'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
