enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  2a29bfd3-16d4-4040-9d07-9781433d328a:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
