enableVersioning: true
handle: thankYou
name: 'Thank you'
propagationMethod: all
siteSettings:
  2a29bfd3-16d4-4040-9d07-9781433d328a:
    enabledByDefault: true
    hasUrls: true
    template: _singles\thank-you
    uriFormat: thank-you
type: single
